name: bigdata_natural_disaster
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  text_neon_widget : ^1.0.6
  syncfusion_flutter_maps: ^30.2.7
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/home_query.png
    - assets/home_model.PNG
    - assets/home_back.jpg
    - assets/world_map.json
  uses-material-design: true